name: Create Production Docker image

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - "release/*"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target branch
        uses: actions/checkout@main

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag vars
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          NAME=${GITHUB_REF_NAME#release/}
          NAME=${NAME//\//-}
          echo "BRANCH_TAG=$NAME" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: MachineService.Server/Dockerfile
          push: true
          tags: |
            duplicati/console-machineserver:${{ env.SHORT_SHA }}
            duplicati/console-machineserver:latest
            duplicati/console-machineserver:${{ env.BRANCH_TAG }}
